" Name:         Solarized 8
" Description:  Precision colors for machines and people
" Authors:      Ethan Schoonover
" Maintainers:  Lifepillar <lifepillar@lifepillar.me>
" URLs:         https://github.com/lifepillar/vim-solarized8
" License:      OSI approved MIT license
" Last Updated: Sat Jun 17 12:56:32 2023

" Generated by Colortemplate v3.0.0-alpha0

hi clear
let g:colors_name = 'solarized8'

let hs_highlight_boolean=1
let hs_highlight_delimiters=1

if &background == 'dark'
  let g:terminal_ansi_colors = ['#073642', '#dc322f', '#859900', '#b58900', '#268bd2', '#d33682', '#2aa198', '#eee8d5', '#002b36', '#cb4b16', '#586e75', '#657b83', '#839496', '#6c71c4', '#93a1a1', '#fdf6e3']

  let s:italics = get(g:, 'solarized_italics', 1) && ((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim'))
  let s:termtrans = get(g:, 'solarized_termtrans', 0) && !has('gui_running')
  let s:visibility = get(g:, 'solarized_visibility', 'normal')
  let s:diffmode = get(g:, 'solarized_diffmode', 'normal')
  let s:stl = get(g:, 'solarized_statusline', 'normal')
  let s:extra = get(g:, 'solarized_extra_hi_groups', 1)
  let s:vismap = {"normal": 0, "high": 1, "low": 2}
  let s:transvis = s:termtrans + 2 * get(s:vismap, s:visibility, 'normal')
  let s:extra_italic = s:extra + 2 * s:italics
  let s:oldcursor = get(g:, 'solarized_old_cursor_style', 0)
  let s:extra_stl = get(g:, 'solarized_extra_hi_groups', 1) + 2 * (get(g:, 'solarized_statusline', '') == 'flat')
  let s:extra_stl_hl = get(g:, 'solarized_extra_hi_groups', 1) + 2 * (get(g:, 'solarized_statusline', '') == 'flat') + 4 * get(g:, 'ale_sign_highlight_linenrs', '')

  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Conditional Statement
  hi! link CurSearch Search
  hi! link CursorLineFold FoldColumn
  hi! link CursorLineSign SignColumn
  hi! link Debug Special
  hi! link Define PreProc
  hi! link Delimiter Special
  hi! link Exception Statement
  hi! link Float Constant
  hi! link Function Identifier
  hi! link Include PreProc
  hi! link Keyword Statement
  hi! link Label Statement
  hi! link LineNrAbove LineNr
  hi! link LineNrBelow LineNr
  hi! link Macro PreProc
  hi! link Number Constant
  hi! link Operator Statement
  hi! link PopupNotification WarningMsg
  hi! link PopupSelected PmenuSel
  hi! link PreCondit PreProc
  hi! link QuickFixLine Search
  hi! link Repeat Statement
  hi! link SpecialChar Special
  hi! link SpecialComment Special
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi! link StorageClass Type
  hi! link String Constant
  hi! link Structure Type
  hi! link Tag Special
  hi! link TermCursor Cursor
  hi! link Typedef Type
  hi! link debugBreakpoint SignColumn
  hi! link debugPC SignColumn
  hi! link lCursor Cursor

  hi Normal guifg=#93a1a1 guibg=#002b36 guisp=NONE gui=NONE
  hi ColorColumn guifg=NONE guibg=#073642 guisp=NONE gui=NONE
  hi CommandMode guifg=#d33682 guibg=#fdf6e3 guisp=NONE gui=reverse
  hi Comment guifg=#586e75 guibg=NONE guisp=NONE gui=italic
  hi Conceal guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
  hi Constant guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE
  hi Cursor guifg=#fdf6e3 guibg=#268bd2 guisp=NONE gui=NONE
  hi CursorColumn guifg=NONE guibg=#073642 guisp=NONE gui=NONE
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE
  hi CursorLine guifg=NONE guibg=#073642 guisp=NONE gui=NONE
  hi CursorLineNr guifg=#839496 guibg=#073642 guisp=NONE gui=bold
  hi DiffAdd guifg=#859900 guibg=#073642 guisp=#859900 gui=NONE
  hi DiffChange guifg=#b58900 guibg=#073642 guisp=#b58900 gui=NONE
  hi DiffDelete guifg=#dc322f guibg=#073642 guisp=NONE gui=bold
  hi DiffText guifg=#268bd2 guibg=#073642 guisp=#268bd2 gui=NONE
  hi Directory guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
  hi EndOfBuffer guifg=NONE guibg=NONE guisp=NONE gui=NONE
  hi Error guifg=#dc322f guibg=#fdf6e3 guisp=NONE gui=bold,reverse
  hi ErrorMsg guifg=#dc322f guibg=#fdf6e3 guisp=NONE gui=reverse
  hi FoldColumn guifg=#839496 guibg=#073642 guisp=NONE gui=NONE
  hi Folded guifg=#839496 guibg=#073642 guisp=#002b36 gui=bold
  hi Identifier guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
  hi Ignore guifg=NONE guibg=NONE guisp=NONE gui=NONE
  hi IncSearch guifg=#cb4b16 guibg=NONE guisp=NONE gui=standout
  hi InsertMode guifg=#2aa198 guibg=#fdf6e3 guisp=NONE gui=reverse
  hi LineNr guifg=#657b83 guibg=#073642 guisp=NONE gui=NONE
  hi MatchParen guifg=#fdf6e3 guibg=#073642 guisp=NONE gui=bold
  hi ModeMsg guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
  hi MoreMsg guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
  hi NonText guifg=#657b83 guibg=NONE guisp=NONE gui=bold
  hi NormalMode guifg=#839496 guibg=#fdf6e3 guisp=NONE gui=reverse
  hi Pmenu guifg=#93a1a1 guibg=#073642 guisp=NONE gui=NONE
  hi PmenuSbar guifg=NONE guibg=#586e75 guisp=NONE gui=NONE
  hi PmenuSel guifg=#eee8d5 guibg=#657b83 guisp=NONE gui=NONE
  hi PmenuThumb guifg=NONE guibg=#839496 guisp=NONE gui=NONE
  hi PreProc guifg=#cb4b16 guibg=NONE guisp=NONE gui=NONE
  hi Question guifg=#2aa198 guibg=NONE guisp=NONE gui=bold
  hi ReplaceMode guifg=#cb4b16 guibg=#fdf6e3 guisp=NONE gui=reverse
  hi Search guifg=#b58900 guibg=NONE guisp=NONE gui=reverse
  hi SignColumn guifg=#839496 guibg=NONE guisp=NONE gui=NONE
  hi Special guifg=#cb4b16 guibg=NONE guisp=NONE gui=NONE
  hi SpecialKey guifg=#657b83 guibg=#073642 guisp=NONE gui=bold
  hi SpellBad guifg=#6c71c4 guibg=NONE guisp=#6c71c4 gui=undercurl
  hi SpellCap guifg=#6c71c4 guibg=NONE guisp=#6c71c4 gui=undercurl
  hi SpellLocal guifg=#b58900 guibg=NONE guisp=#b58900 gui=undercurl
  hi SpellRare guifg=#2aa198 guibg=NONE guisp=#2aa198 gui=undercurl
  hi Statement guifg=#859900 guibg=NONE guisp=NONE gui=NONE
  hi StatusLine guifg=#839496 guibg=#073642 guisp=NONE gui=reverse
  hi StatusLineNC guifg=#586e75 guibg=#073642 guisp=NONE gui=reverse
  hi TabLine guifg=#586e75 guibg=#073642 guisp=NONE gui=reverse
  hi TabLineFill guifg=#586e75 guibg=#073642 guisp=NONE gui=reverse
  hi TabLineSel guifg=#839496 guibg=#073642 guisp=NONE gui=reverse
  hi TermCursorNC guifg=#002b36 guibg=#586e75 guisp=NONE gui=NONE
  hi Terminal guifg=fg guibg=#002b36 guisp=NONE gui=NONE
  hi Title guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold
  hi Todo guifg=#d33682 guibg=NONE guisp=NONE gui=bold
  hi ToolbarButton guifg=#93a1a1 guibg=#073642 guisp=NONE gui=bold
  hi ToolbarLine guifg=NONE guibg=#073642 guisp=NONE gui=NONE
  hi Type guifg=#b58900 guibg=NONE guisp=NONE gui=NONE
  hi Underlined guifg=#6c71c4 guibg=NONE guisp=NONE gui=NONE
  hi VertSplit guifg=#073642 guibg=#586e75 guisp=NONE gui=NONE
  hi Visual guifg=#586e75 guibg=#002b36 guisp=NONE gui=reverse
  hi VisualMode guifg=#d33682 guibg=#fdf6e3 guisp=NONE gui=reverse
  hi VisualNOS guifg=NONE guibg=#073642 guisp=NONE gui=reverse
  hi WarningMsg guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold
  hi WildMenu guifg=#eee8d5 guibg=#073642 guisp=NONE gui=reverse

  if has('gui_running')
    if s:diffmode == "high"
      hi DiffAdd guifg=#859900 guibg=NONE guisp=NONE gui=reverse
      hi DiffChange guifg=#b58900 guibg=NONE guisp=NONE gui=reverse
      hi DiffDelete guifg=#dc322f guibg=NONE guisp=NONE gui=reverse
      hi DiffText guifg=#268bd2 guibg=NONE guisp=NONE gui=reverse
    elseif s:diffmode == "low"
      hi DiffAdd guifg=#859900 guibg=NONE guisp=#859900 gui=NONE
      hi DiffChange guifg=#b58900 guibg=NONE guisp=#b58900 gui=NONE
      hi DiffDelete guifg=#dc322f guibg=NONE guisp=NONE gui=bold
      hi DiffText guifg=#268bd2 guibg=NONE guisp=#268bd2 gui=NONE
    endif
    if s:extra == 1
      hi ALEError guifg=#dc322f guibg=NONE guisp=#dc322f gui=undercurl
      hi ALEErrorLine guifg=NONE guibg=NONE guisp=NONE gui=NONE
      hi ALEInfo guifg=#2aa198 guibg=NONE guisp=#2aa198 gui=undercurl
      hi ALEInfoLine guifg=NONE guibg=NONE guisp=NONE gui=NONE
      hi! link ALEStyleError ALEError
      hi! link ALEStyleErrorSign ALEErrorSign
      hi! link ALEStyleErrorSignLineNr ALEErrorSignLineNr
      hi! link ALEStyleWarning ALEWarning
      hi! link ALEStyleWarningSign ALEWarningSign
      hi! link ALEStyleWarningSignLineNr ALEWarningSignLineNr
      hi ALEWarning guifg=#b58900 guibg=NONE guisp=#b58900 gui=undercurl
      hi ALEWarningLine guifg=NONE guibg=NONE guisp=NONE gui=NONE
      hi ConId guifg=#b58900 guibg=NONE guisp=NONE gui=NONE
      hi VarId guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
      hi cPreCondit guifg=#cb4b16 guibg=NONE guisp=NONE gui=NONE
      hi! link diffAdded Statement
      hi! link diffLine Identifier
      hi gitcommitBranch guifg=#d33682 guibg=NONE guisp=NONE gui=bold
      hi! link gitcommitDiscarded gitcommitComment
      hi! link gitcommitDiscardedArrow gitcommitDiscardedFile
      hi gitcommitDiscardedFile guifg=#dc322f guibg=NONE guisp=NONE gui=bold
      hi gitcommitFile guifg=#839496 guibg=NONE guisp=NONE gui=bold
      hi gitcommitHeader guifg=#586e75 guibg=NONE guisp=NONE gui=NONE
      hi! link gitcommitNoBranch gitcommitBranch
      hi gitcommitOnBranch guifg=#586e75 guibg=NONE guisp=NONE gui=bold
      hi! link gitcommitSelected gitcommitComment
      hi! link gitcommitSelectedArrow gitcommitSelectedFile
      hi gitcommitSelectedFile guifg=#859900 guibg=NONE guisp=NONE gui=bold
      hi gitcommitUnmerged guifg=#859900 guibg=NONE guisp=NONE gui=bold
      hi! link gitcommitUnmergedArrow gitcommitUnmergedFile
      hi gitcommitUnmergedFile guifg=#b58900 guibg=NONE guisp=NONE gui=bold
      hi! link gitcommitUntracked gitcommitComment
      hi gitcommitUntrackedFile guifg=#2aa198 guibg=NONE guisp=NONE gui=bold
      hi gitcommitdiscardedtype guifg=#dc322f guibg=NONE guisp=NONE gui=NONE
      hi gitcommitselectedtype guifg=#859900 guibg=NONE guisp=NONE gui=NONE
      hi helpExample guifg=#93a1a1 guibg=NONE guisp=NONE gui=NONE
      hi helpHyperTextEntry guifg=#859900 guibg=NONE guisp=NONE gui=NONE
      hi helpHyperTextJump guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
      hi helpNote guifg=#d33682 guibg=NONE guisp=NONE gui=NONE
      hi helpOption guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE
      hi! link helpSpecial Special
      hi helpVim guifg=#d33682 guibg=NONE guisp=NONE gui=NONE
      hi! link hsDelimTypeExport Delimiter
      hi hsImport guifg=#d33682 guibg=NONE guisp=NONE gui=NONE
      hi hsImportLabel guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE
      hi! link hsImportParams Delimiter
      hi hsModuleName guifg=#859900 guibg=NONE guisp=NONE gui=NONE
      hi! link hsModuleStartLabel hsStructure
      hi! link hsModuleWhereLabel hsModuleStartLabel
      hi hsNiceOperator guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE
      hi hsStatement guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE
      hi hsString guifg=#657b83 guibg=NONE guisp=NONE gui=NONE
      hi hsStructure guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE
      hi hsType guifg=#b58900 guibg=NONE guisp=NONE gui=NONE
      hi hsTypedef guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE
      hi hsVarSym guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE
      hi hs_DeclareFunction guifg=#cb4b16 guibg=NONE guisp=NONE gui=NONE
      hi hs_OpFunctionName guifg=#b58900 guibg=NONE guisp=NONE gui=NONE
      hi hs_hlFunctionName guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
      hi hsniceoperator guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE
      hi htmlArg guifg=#657b83 guibg=NONE guisp=NONE gui=NONE
      hi htmlEndTag guifg=#586e75 guibg=NONE guisp=NONE gui=NONE
      hi htmlTag guifg=#586e75 guibg=NONE guisp=NONE gui=NONE
      hi htmlTagN guifg=#93a1a1 guibg=NONE guisp=NONE gui=bold
      hi htmlTagName guifg=#268bd2 guibg=NONE guisp=NONE gui=bold
      hi javaScript guifg=#b58900 guibg=NONE guisp=NONE gui=NONE
      hi! link jsFuncCall Function
      hi pandocBlockQuote guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
      hi pandocBlockQuoteLeader1 guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
      hi pandocBlockQuoteLeader2 guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE
      hi pandocBlockQuoteLeader3 guifg=#b58900 guibg=NONE guisp=NONE gui=NONE
      hi pandocBlockQuoteLeader4 guifg=#dc322f guibg=NONE guisp=NONE gui=NONE
      hi pandocBlockQuoteLeader5 guifg=#839496 guibg=NONE guisp=NONE gui=NONE
      hi pandocBlockQuoteLeader6 guifg=#586e75 guibg=NONE guisp=NONE gui=NONE
      hi pandocCitation guifg=#d33682 guibg=NONE guisp=NONE gui=NONE
      hi pandocCitationDelim guifg=#d33682 guibg=NONE guisp=NONE gui=NONE
      hi pandocCitationID guifg=#d33682 guibg=NONE guisp=NONE gui=NONE
      hi pandocCitationRef guifg=#d33682 guibg=NONE guisp=NONE gui=NONE
      hi! link pandocCodeBlock pandocVerbatimBlock
      hi! link pandocCodeBlockDelim pandocVerbatimBlock
      hi pandocDefinitionBlock guifg=#6c71c4 guibg=NONE guisp=NONE gui=NONE
      hi pandocDefinitionIndctr guifg=#6c71c4 guibg=NONE guisp=NONE gui=bold
      hi pandocDefinitionTerm guifg=#6c71c4 guibg=NONE guisp=NONE gui=standout
      hi pandocEmphasisHeading guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold
      hi pandocEmphasisNested guifg=#839496 guibg=NONE guisp=NONE gui=bold
      hi pandocEmphasisNestedDefinition guifg=#6c71c4 guibg=NONE guisp=NONE gui=bold
      hi pandocEmphasisNestedHeading guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold
      hi pandocEmphasisNestedTable guifg=#268bd2 guibg=NONE guisp=NONE gui=bold
      hi pandocEscapePair guifg=#dc322f guibg=NONE guisp=NONE gui=bold
      hi! link pandocEscapedCharacter pandocEscapePair
      hi pandocFootnote guifg=#859900 guibg=NONE guisp=NONE gui=NONE
      hi pandocFootnoteDefLink guifg=#859900 guibg=NONE guisp=NONE gui=bold
      hi pandocFootnoteInline guifg=#859900 guibg=NONE guisp=NONE gui=bold
      hi pandocFootnoteLink guifg=#859900 guibg=NONE guisp=NONE gui=NONE
      hi pandocHeading guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold
      hi pandocHeadingMarker guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold
      hi pandocImageCaption guifg=#6c71c4 guibg=NONE guisp=NONE gui=bold
      hi! link pandocLineBreak pandocEscapePair
      hi pandocLinkDefinition guifg=#2aa198 guibg=NONE guisp=#657b83 gui=NONE
      hi pandocLinkDefinitionID guifg=#268bd2 guibg=NONE guisp=NONE gui=bold
      hi pandocLinkDelim guifg=#586e75 guibg=NONE guisp=NONE gui=NONE
      hi pandocLinkLabel guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
      hi pandocLinkText guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
      hi pandocLinkTitle guifg=#657b83 guibg=NONE guisp=NONE gui=NONE
      hi pandocLinkTitleDelim guifg=#586e75 guibg=NONE guisp=#657b83 gui=NONE
      hi pandocLinkURL guifg=#657b83 guibg=NONE guisp=NONE gui=NONE
      hi pandocListMarker guifg=#d33682 guibg=NONE guisp=NONE gui=NONE
      hi pandocListReference guifg=#d33682 guibg=NONE guisp=NONE gui=NONE
      hi pandocMetadata guifg=#268bd2 guibg=NONE guisp=NONE gui=bold
      hi pandocMetadataDelim guifg=#586e75 guibg=NONE guisp=NONE gui=NONE
      hi pandocMetadataKey guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
      hi! link pandocMetadataTitle pandocMetadata
      hi pandocNonBreakingSpace guifg=#dc322f guibg=NONE guisp=NONE gui=reverse
      hi pandocRule guifg=#268bd2 guibg=NONE guisp=NONE gui=bold
      hi pandocRuleLine guifg=#268bd2 guibg=NONE guisp=NONE gui=bold
      hi pandocStrikeout guifg=#586e75 guibg=NONE guisp=NONE gui=reverse
      hi pandocStrikeoutDefinition guifg=#6c71c4 guibg=NONE guisp=NONE gui=reverse
      hi pandocStrikeoutHeading guifg=#cb4b16 guibg=NONE guisp=NONE gui=reverse
      hi pandocStrikeoutTable guifg=#268bd2 guibg=NONE guisp=NONE gui=reverse
      hi pandocStrongEmphasis guifg=#839496 guibg=NONE guisp=NONE gui=bold
      hi pandocStrongEmphasisDefinition guifg=#6c71c4 guibg=NONE guisp=NONE gui=bold
      hi pandocStrongEmphasisEmphasis guifg=#839496 guibg=NONE guisp=NONE gui=bold
      hi pandocStrongEmphasisEmphasisDefinition guifg=#6c71c4 guibg=NONE guisp=NONE gui=bold
      hi pandocStrongEmphasisEmphasisHeading guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold
      hi pandocStrongEmphasisEmphasisTable guifg=#268bd2 guibg=NONE guisp=NONE gui=bold
      hi pandocStrongEmphasisHeading guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold
      hi pandocStrongEmphasisNested guifg=#839496 guibg=NONE guisp=NONE gui=bold
      hi pandocStrongEmphasisNestedDefinition guifg=#6c71c4 guibg=NONE guisp=NONE gui=bold
      hi pandocStrongEmphasisNestedHeading guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold
      hi pandocStrongEmphasisNestedTable guifg=#268bd2 guibg=NONE guisp=NONE gui=bold
      hi pandocStrongEmphasisTable guifg=#268bd2 guibg=NONE guisp=NONE gui=bold
      hi pandocStyleDelim guifg=#586e75 guibg=NONE guisp=NONE gui=NONE
      hi pandocSubscript guifg=#6c71c4 guibg=NONE guisp=NONE gui=NONE
      hi pandocSubscriptDefinition guifg=#6c71c4 guibg=NONE guisp=NONE gui=NONE
      hi pandocSubscriptHeading guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold
      hi pandocSubscriptTable guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
      hi pandocSuperscript guifg=#6c71c4 guibg=NONE guisp=NONE gui=NONE
      hi pandocSuperscriptDefinition guifg=#6c71c4 guibg=NONE guisp=NONE gui=NONE
      hi pandocSuperscriptHeading guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold
      hi pandocSuperscriptTable guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
      hi pandocTable guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
      hi pandocTableStructure guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
      hi! link pandocTableStructureEnd pandocTableStructre
      hi! link pandocTableStructureTop pandocTableStructre
      hi pandocTableZebraDark guifg=#268bd2 guibg=#073642 guisp=NONE gui=NONE
      hi pandocTableZebraLight guifg=#268bd2 guibg=#002b36 guisp=NONE gui=NONE
      hi pandocTitleBlock guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
      hi pandocTitleBlockTitle guifg=#268bd2 guibg=NONE guisp=NONE gui=bold
      hi pandocTitleComment guifg=#268bd2 guibg=NONE guisp=NONE gui=bold
      hi pandocVerbatimBlock guifg=#b58900 guibg=NONE guisp=NONE gui=NONE
      hi! link pandocVerbatimBlockDeep pandocVerbatimBlock
      hi pandocVerbatimInline guifg=#b58900 guibg=NONE guisp=NONE gui=NONE
      hi pandocVerbatimInlineDefinition guifg=#6c71c4 guibg=NONE guisp=NONE gui=NONE
      hi pandocVerbatimInlineHeading guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold
      hi pandocVerbatimInlineTable guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
      hi perlHereDoc guifg=#93a1a1 guibg=NONE guisp=NONE gui=NONE
      hi perlStatementFileDesc guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE
      hi perlVarPlain guifg=#b58900 guibg=NONE guisp=NONE gui=NONE
      hi rubyBoolean guifg=#d33682 guibg=NONE guisp=NONE gui=NONE
      hi rubyDefine guifg=#93a1a1 guibg=NONE guisp=NONE gui=bold
      hi! link rubySymbol Type
      hi texmathmatcher guifg=#b58900 guibg=NONE guisp=NONE gui=NONE
      hi texmathzonex guifg=#b58900 guibg=NONE guisp=NONE gui=NONE
      hi texreflabel guifg=#b58900 guibg=NONE guisp=NONE gui=NONE
      hi texstatement guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE
      hi vimCmdSep guifg=#268bd2 guibg=NONE guisp=NONE gui=bold
      hi vimCommand guifg=#b58900 guibg=NONE guisp=NONE gui=NONE
      hi vimCommentString guifg=#6c71c4 guibg=NONE guisp=NONE gui=NONE
      hi! link vimFunc Function
      hi vimGroup guifg=#268bd2 guibg=NONE guisp=NONE gui=bold
      hi vimHiGroup guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
      hi vimHiLink guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
      hi vimIsCommand guifg=#657b83 guibg=NONE guisp=NONE gui=NONE
      hi vimSynMtchOpt guifg=#b58900 guibg=NONE guisp=NONE gui=NONE
      hi vimSynType guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE
      hi! link vimUserFunc Function
      hi! link vimVar Identifier
    endif
    if s:extra_italic == 1
      hi gitcommitComment guifg=#586e75 guibg=NONE guisp=NONE gui=NONE
      hi htmlSpecialTagName guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
      hi pandocComment guifg=#586e75 guibg=NONE guisp=NONE gui=NONE
      hi pandocEmphasis guifg=#839496 guibg=NONE guisp=NONE gui=NONE
      hi pandocEmphasisDefinition guifg=#6c71c4 guibg=NONE guisp=NONE gui=NONE
      hi pandocEmphasisTable guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE
    elseif s:extra_italic == 3
      hi gitcommitComment guifg=#586e75 guibg=NONE guisp=NONE gui=italic
      hi htmlSpecialTagName guifg=#268bd2 guibg=NONE guisp=NONE gui=italic
      hi pandocComment guifg=#586e75 guibg=NONE guisp=NONE gui=italic
      hi pandocEmphasis guifg=#839496 guibg=NONE guisp=NONE gui=italic
      hi pandocEmphasisDefinition guifg=#6c71c4 guibg=NONE guisp=NONE gui=italic
      hi pandocEmphasisTable guifg=#268bd2 guibg=NONE guisp=NONE gui=italic
    endif
    if s:extra_stl == 1
      hi ALEErrorSignLineNr guifg=#073642 guibg=#dc322f guisp=NONE gui=NONE
      hi ALEInfoSignLineNr guifg=#073642 guibg=#2aa198 guisp=NONE gui=NONE
      hi ALEWarningSignLineNr guifg=#073642 guibg=#b58900 guisp=NONE gui=NONE
    elseif s:extra_stl == 3
      hi ALEErrorSignLineNr guifg=#dc322f guibg=NONE guisp=NONE gui=NONE
      hi ALEInfoSignLineNr guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE
      hi ALEWarningSignLineNr guifg=#b58900 guibg=NONE guisp=NONE gui=NONE
    endif
    if s:extra_stl_hl == 1
      hi ALEErrorSign guifg=#dc322f guibg=#073642 guisp=NONE gui=bold
      hi ALEInfoSign guifg=#2aa198 guibg=#073642 guisp=NONE gui=bold
      hi ALEWarningSign guifg=#b58900 guibg=#073642 guisp=NONE gui=bold
    elseif s:extra_stl_hl == 3
      hi ALEErrorSign guifg=#dc322f guibg=NONE guisp=NONE gui=bold
      hi ALEInfoSign guifg=#2aa198 guibg=NONE guisp=NONE gui=bold
      hi ALEWarningSign guifg=#b58900 guibg=NONE guisp=NONE gui=bold
    elseif s:extra_stl_hl == 5
      hi ALEErrorSign guifg=#073642 guibg=#dc322f guisp=NONE gui=bold
      hi ALEInfoSign guifg=#073642 guibg=#2aa198 guisp=NONE gui=bold
      hi ALEWarningSign guifg=#073642 guibg=#b58900 guisp=NONE gui=bold
    endif
    if s:italics == 0
      hi Comment gui=NONE
    endif
    if s:oldcursor == 1
      hi Cursor guifg=#002b36 guibg=#839496 guisp=NONE gui=NONE
    endif
    if s:stl == "flat"
      hi StatusLine guifg=#073642 guibg=#eee8d5 guisp=NONE gui=reverse
      hi StatusLineNC guifg=#073642 guibg=#93a1a1 guisp=NONE gui=reverse
      hi TabLine guifg=#586e75 guibg=#073642 guisp=NONE gui=NONE
      hi TabLineFill guifg=#586e75 guibg=#073642 guisp=NONE gui=NONE
      hi TabLineSel guifg=#eee8d5 guibg=#073642 guisp=NONE gui=NONE
      hi VertSplit guifg=#586e75 guibg=#073642 guisp=NONE gui=NONE
    elseif s:stl == "low"
      hi StatusLine guifg=#586e75 guibg=#eee8d5 guisp=NONE gui=reverse
      hi StatusLineNC guifg=#586e75 guibg=#073642 guisp=NONE gui=reverse
      hi TabLine guifg=#586e75 guibg=#073642 guisp=NONE gui=reverse
      hi TabLineFill guifg=#586e75 guibg=#073642 guisp=NONE gui=reverse
      hi TabLineSel guifg=#839496 guibg=#fdf6e3 guisp=NONE gui=reverse
      hi VertSplit guifg=#073642 guibg=#586e75 guisp=NONE gui=NONE
    endif
    if s:transvis == 1
      hi CursorLineNr guifg=#839496 guibg=NONE guisp=NONE gui=bold
      hi LineNr guifg=#657b83 guibg=NONE guisp=NONE gui=NONE
    elseif s:transvis == 2
      hi CursorLineNr guifg=#cb4b16 guibg=#073642 guisp=NONE gui=bold
      hi LineNr guifg=#839496 guibg=#073642 guisp=NONE gui=NONE
    elseif s:transvis == 3
      hi CursorLineNr guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold
      hi LineNr guifg=#839496 guibg=NONE guisp=NONE gui=NONE
    elseif s:transvis == 4
      hi CursorLineNr guifg=#586e75 guibg=#073642 guisp=NONE gui=bold
      hi LineNr guifg=#586e75 guibg=#073642 guisp=NONE gui=NONE
    elseif s:transvis == 5
      hi CursorLineNr guifg=#586e75 guibg=NONE guisp=NONE gui=bold
      hi LineNr guifg=#586e75 guibg=NONE guisp=NONE gui=NONE
    endif
    if s:visibility == "high"
      hi NonText guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold
      hi SpecialKey guifg=#cb4b16 guibg=NONE guisp=NONE gui=reverse
      hi SpellBad guifg=#6c71c4 guibg=#fdf6e3 guisp=#dc322f gui=reverse,undercurl
      hi SpellCap guifg=#6c71c4 guibg=#fdf6e3 guisp=#dc322f gui=reverse,undercurl
      hi SpellLocal guifg=#b58900 guibg=#fdf6e3 guisp=#dc322f gui=reverse,undercurl
      hi SpellRare guifg=#2aa198 guibg=#fdf6e3 guisp=#dc322f gui=reverse,undercurl
      hi Title guifg=#b58900 guibg=NONE guisp=NONE gui=bold
    elseif s:visibility == "low"
      hi NonText guifg=#073642 guibg=NONE guisp=NONE gui=bold
      hi SpecialKey guifg=#073642 guibg=NONE guisp=NONE gui=reverse
      hi Title guifg=#586e75 guibg=NONE guisp=NONE gui=bold
    endif
  endif
endif

