name: "Dotfiles CI"
jobs:
  ubuntu-2004:
    runs-on: ubuntu-20.04
    container: {image: ubuntu:20.04}
    steps:
      - name: Container Prep
        run: |
          apt-get update -qq
          DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends sudo software-properties-common
        
      - name: Install Chezmoi
        run: |
          sudo apt-get update -qq && sudo apt-get install -qq -y curl
          sudo sh -c "$(curl -fsLS https://chezmoi.io/get)" -- -b /usr/bin/

      - name: Chezmoi Init & Apply
        run: |
          chezmoi -S ${GITHUB_WORKSPACE} init --apply --promptString "What is your full name=Example,What is your email=name@example.org"

  fedora-39:
    runs-on: ubuntu-20.04
    container: {image: fedora:39}
    steps:
      - name: Checkout Dotfiles
        uses: actions/checkout@v4

      - name: Install Chezmoi
        run: |
          sudo sh -c "$(curl -fsLS https://chezmoi.io/get)" -- -b /usr/bin/

      - name: Chezmoi Init
        run: |
          chezmoi -S ${GITHUB_WORKSPACE} init --apply --promptString "What is your full name=Example,What is your email=name@example.org"

