name: "Dotfiles CI"
on: push
jobs:
  ubuntu-2004:
    runs-on: ubuntu-20.04
    container: {image: 'ubuntu:20.04'}
    steps:
      - name: Checkout Dotfiles
        uses: actions/checkout@v4

      - name: Container Prep
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends sudo software-properties-common
          apt-get install -y fontconfig curl
        
      - name: Install Chezmoi
        run: |
          sudo sh -c "$(curl -fsLS https://chezmoi.io/get)" -- -b /usr/bin/

      - name: Chezmoi Init & Apply
        run: |
          chezmoi -S ${GITHUB_WORKSPACE} init --apply --promptString "What is your full name=Example,What is your email=name@example.org"

  fedora-39:
    runs-on: ubuntu-20.04
    container: {image: 'fedora:39'}
    steps:
      - name: Checkout Dotfiles
        uses: actions/checkout@v4

      - name: Install Chezmoi
        run: |
          sudo sh -c "$(curl -fsLS https://chezmoi.io/get)" -- -b /usr/bin/

      - name: Chezmoi Init
        run: |
          chezmoi -S ${GITHUB_WORKSPACE} init --apply --promptString "What is your full name=Example,What is your email=name@example.org"

