name: "Dotfiles CI"
on: push
jobs:


  linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: ['ubuntu:20.04', 'fedora:39']
    container:
      image: ${{ matrix.os }}
    steps:
      - name: Checkout dotfiles
        uses: actions/checkout@v4

      - name: Container prep
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends sudo software-properties-common
          apt-get install -y fontconfig curl

      - name: Install Chezmoi, init, & apply
        uses: ./.github/actions/chezmoi


  macos:
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - name: Checkout dotfiles
        uses: actions/checkout@v4

      - name: Install Chezmoi, init, & apply
        uses: ./.github/actions/chezmoi
